//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Mews.Fiscalizations.Basque.Dto;

using System;
using System.Xml.Serialization;
using System.ComponentModel;
using System.CodeDom.Compiler;

/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable]
[System.Diagnostics.DebuggerStepThroughAttribute]
[DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "urn:ticketbai:anulacion")]
[XmlRoot(Namespace = "urn:ticketbai:anulacion", IsNullable = false)]
public class AnulaTicketBai
{

    private Cabecera cabeceraField;

    private IDFactura iDFacturaField;

    private HuellaTBAI huellaTBAIField;

    private SignatureType signatureField;

    /// <remarks/>
    [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Cabecera Cabecera
    {
        get
        {
            return cabeceraField;
        }
        set
        {
            cabeceraField = value;
        }
    }

    /// <remarks/>
    [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IDFactura IDFactura
    {
        get
        {
            return iDFacturaField;
        }
        set
        {
            iDFacturaField = value;
        }
    }

    /// <remarks/>
    [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public HuellaTBAI HuellaTBAI
    {
        get
        {
            return huellaTBAIField;
        }
        set
        {
            huellaTBAIField = value;
        }
    }

    /// <remarks/>
    [XmlElement(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public SignatureType Signature
    {
        get
        {
            return signatureField;
        }
        set
        {
            signatureField = value;
        }
    }
}